services:
  currency-rate-extractor:
    image: currency-rate-extractor
    build:
      context: .
      dockerfile: Web/Dockerfile
    networks:
      - mongo-main
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:8080"
      - "8081:8081"
  
  mongo-main:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - mongo-main
    environment:
      - MONGO_INITDB_ROOT_USERNAME=MainUser
      - MONGO_INITDB_ROOT_PASSWORD=Test123!
      - MONGO_INITDB_DATABASE=CurrencyRates

  mongo-logs:
    image: mongo:latest
    ports:
      - "27037:27017"
    networks:
      - mongo-main
    environment:
      - MONGO_INITDB_ROOT_USERNAME=MainUser
      - MONGO_INITDB_ROOT_PASSWORD=Test123!
      - MONGO_INITDB_DATABASE=Logging

networks:
  mongo-main: